$('.slider').owlCarousel({
    loop:true,
    autoplay:true,
    autoplayTimeout:5000,
    smartSpeed:500,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})

$('.sliderText').owlCarousel({
    loop:true,
    autoplay:true,
    autoplayTimeout:10000,
    smartSpeed:500,
    responsive:{
        0:{
            items:1
        },
        600:{
            items:1
        },
        1000:{
            items:1
        }
    }
})
